[package]
name = "advent-of-code-2023-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
memoize = "0.4.0"
anyhow = "1.0.75"
itertools = "0.12.0"
reqwest = { version = "0.11.22", features = ["blocking"] }
chrono = "0.4.31"
chrono-tz = "0.8.4"
