[package]
name = "advent-of-code-2023-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.7.0"
lazy_static = "1.4.0"
memoize = "0.4.0"
anyhow = "1.0.75"
datetime = "0.5.2"
itertools = "0.12.0"
reqwest = { version = "0.11.22", features = ["blocking"] }
